### ISSUE TITLE
只收货不换建筑分辨率适配版2.2 bug

### ISSUE THREAD

**Issue by Avwqs** [aersi/jgm_autoload#1]
使用这个版本，升级政策的时候打开政策，关掉那个已完成政策通知，然后就关掉政策界面了，再然后就是一直收竖着中间那行金币不动了。手机1080*1920
![Screenshot_2019-10-11-13-14-58-221_com tencent jgm](https://user-images.githubusercontent.com/32660279/66626434-cb979000-ec2a-11e9-8c31-b67a5afc0147.png)

**Comment by aersi** [comment]
感谢您提交反馈，政策中心的问题是确认操作点击太靠下，按到了底部的建设按钮，已经调高了，你试一下。
收钱的问题我没发现啊，你再看看

---原始邮件---
发件人: "Avwqs"<notifications@github.com&gt;
发送时间: 2019年10月11日(星期五) 中午1:27
收件人: "aersi/jgm_autoload"<jgm_autoload@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [aersi/jgm_autoload] 只收货不换建筑分辨率适配版2.2 bug (#1)



使用这个版本，升级政策的时候打开政策，关掉那个已完成政策通知，然后就关掉政策界面了，再然后就是一直收竖着中间那行金币不动了。手机1080*1920

**Comment by Avwqs** [comment]
已解决，谢谢
